### ISSUE TITLE
[UI] Put watch, star and fork icon action to repo page 

### ISSUE THREAD

**Issue by maxloh** [pd4d10/git-touch#17]
Hi. Would you consider putting watch, star and fork action in the repo page instead of the three dot menu?

User may press the star/watch/fork icon to star/watch/fork a repo and press star/watch/fork count to view watchers/stargazers/forks of a repo.

![screenshot-android](https://user-images.githubusercontent.com/35831069/70731223-5129e000-1d41-11ea-8a5c-d6d724dd9fe7.png)

**Comment by pd4d10** [comment]
Hi, @maxloh , thanks for your feedback! Because the count area tap event is to go to watchers/stargazers screen, so we add an extra row to do watch/star action. Does this meet your needs?

The fork action is not ready yet, because it is related to code editing and pull requests creating, and these processes have not been implemented in this app yet.

### Screenshot

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-09 at 10 50 55](https://user-images.githubusercontent.com/9524411/74095321-10c0c580-4b2a-11ea-8cd0-57d5dd421e82.png)

**Comment by maxloh** [comment]
> count area

The user interface in v1.4.0 meet my needs, but it would be better if you could put action buttons next to the count area.

Thank you.

**Comment by pd4d10** [comment]
OK. Considering the mobile screen small size, we didn't put them together as the GitHub website does.

Thanks for your feedback! Feel free to open another issue if there are other problems.
